### ISSUE TITLE
Plugin not working on Ruby 2.1.3 with Cocoapods 0.39.0

### ISSUE THREAD

**Issue by Ashton-W** [orta/cocoapods-always-be-bundleing#2]
### Error

```
NoMethodError - undefined method `install_before_always_be_bundling!' for #<Pod::Installer:0x007fd6f4816938>
/Users/AshtonWilliams/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-always-be-bundleing-0.0.3/lib/cocoapods_plugin.rb:9:in `install!'
/Users/AshtonWilliams/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/AshtonWilliams/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/AshtonWilliams/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/AshtonWilliams/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/AshtonWilliams/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/AshtonWilliams/.rbenv/versions/2.1.3/bin/pod:23:in `load'
/Users/AshtonWilliams/.rbenv/versions/2.1.3/bin/pod:23:in `<main>'
```

I'll try and look into this myself later, but it looks like it could simply be method name needs to change, could be a quick fix.
